version: "3.8"
services:
  server:
    ports:
      - 80:80
    restart: always
    build:
      context: docker
      dockerfile: server.Dockerfile
    volumes:
      - ./configuration/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/src
  # TODO: Сделать автоматическое резервное копирование БД в конце каждого дня по UTC 0+
  db:
    ports:
      - 5432:5432
    restart: always
    build:
      context: docker
      dockerfile: db.Dockerfile
    env_file:
      - configuration/db.env
    volumes:
      - .:/docker-entrypoint-initdb.d
      - dbdata:/var/lib/postgresql/data
      - ./db:/var/www/db
  
  app:
    restart: always
    build:
      context: docker
      dockerfile: app.Dockerfile
    env_file:
      - configuration/xdebug.env
    volumes:
      - ./src:/var/www/src
      - ./configuration/php.ini:/usr/local/etc/php/php.ini:ro
  
  composer:
    build:
      context: docker
      dockerfile: composer.Dockerfile
    volumes:
      - ./src:/var/www/src
  
  view:
    build:
      context: docker
      dockerfile: view.Dockerfile
    volumes:
      - ./src:/var/www/src
    
  artisan:
    build:
      context: docker
      dockerfile: app.Dockerfile
    volumes:
      - ./src:/var/www/src
    entrypoint: ["php", "/var/www/src/artisan"]

volumes:
  dbdata:
    driver: local